/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Canteen1;

import Canteen1.Wellcome;

/**
 *
 * @author Anik
 */
public class Canteen extends javax.swing.JFrame {

  double []i= new double[20];  
  int []c={100,50,20,10,5,2,1};
    public Canteen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jCheckSingara = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jCheckSomosa = new javax.swing.JCheckBox();
        jCheckNoodles = new javax.swing.JCheckBox();
        jCheckBurger = new javax.swing.JCheckBox();
        jCheckChickenRoll = new javax.swing.JCheckBox();
        jCheckPizza = new javax.swing.JCheckBox();
        jTextsingara = new javax.swing.JTextField();
        jTextsomosa = new javax.swing.JTextField();
        jTextnoodles = new javax.swing.JTextField();
        jTextburger = new javax.swing.JTextField();
        jTextchickenroll = new javax.swing.JTextField();
        jTextpizza = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jCheckPepsi = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jCheckCocacola = new javax.swing.JCheckBox();
        jCheck7up = new javax.swing.JCheckBox();
        jCheckMuntainDew = new javax.swing.JCheckBox();
        jTextpepsi = new javax.swing.JTextField();
        jTextcocacola = new javax.swing.JTextField();
        jText7up = new javax.swing.JTextField();
        jTextmountaindew = new javax.swing.JTextField();
        jCheckTea = new javax.swing.JCheckBox();
        jTexttea = new javax.swing.JTextField();
        jTextcoffee = new javax.swing.JTextField();
        jCheckCofee = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlblCostoffoods = new javax.swing.JLabel();
        jlblCostofdrinks = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jlblsubTotal = new javax.swing.JLabel();
        jlblVat = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jcmbCurrency = new javax.swing.JComboBox<>();
        jlblConvert = new javax.swing.JLabel();
        jBtnConvert = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jlblNetpayable = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jlblRetuenamount = new javax.swing.JLabel();
        jTextCashpaid = new javax.swing.JTextField();
        jBtncalculate = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jBtnTotal = new javax.swing.JButton();
        jBtnReceipt = new javax.swing.JButton();
        jBtnReset = new javax.swing.JButton();
        jBtnExit = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1350, 730));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Name Of Foods");

        jSeparator1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 255)));

        jCheckSingara.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckSingara.setText("Singara");
        jCheckSingara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckSingaraMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Qty");

        jCheckSomosa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckSomosa.setText("Samosa");
        jCheckSomosa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckSomosaMouseClicked(evt);
            }
        });

        jCheckNoodles.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckNoodles.setText("Noodles");
        jCheckNoodles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckNoodlesMouseClicked(evt);
            }
        });

        jCheckBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBurger.setText("Burger");
        jCheckBurger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBurgerMouseClicked(evt);
            }
        });

        jCheckChickenRoll.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckChickenRoll.setText("Chicken Roll");
        jCheckChickenRoll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckChickenRollMouseClicked(evt);
            }
        });

        jCheckPizza.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckPizza.setText("Pizza");
        jCheckPizza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckPizzaMouseClicked(evt);
            }
        });

        jTextsingara.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextsingara.setText("0");
        jTextsingara.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextsomosa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextsomosa.setText("0");
        jTextsomosa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextnoodles.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextnoodles.setText("0");
        jTextnoodles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextburger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextburger.setText("0");
        jTextburger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextchickenroll.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextchickenroll.setText("0");
        jTextchickenroll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextpizza.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextpizza.setText("0");
        jTextpizza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(53, 53, 53))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckSomosa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextsomosa, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckSingara)
                                    .addComponent(jCheckPizza)
                                    .addComponent(jCheckChickenRoll)
                                    .addComponent(jCheckBurger)
                                    .addComponent(jCheckNoodles))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextsingara)
                                    .addComponent(jTextnoodles, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(jTextburger)
                                    .addComponent(jTextchickenroll)
                                    .addComponent(jTextpizza))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckSingara)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextsingara)
                        .addGap(3, 3, 3)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckSomosa)
                    .addComponent(jTextsomosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckNoodles)
                    .addComponent(jTextnoodles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBurger)
                    .addComponent(jTextburger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckChickenRoll)
                    .addComponent(jTextchickenroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckPizza)
                    .addComponent(jTextpizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Name Of Drinks");

        jSeparator2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 255)));

        jCheckPepsi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckPepsi.setText("Pepsi");
        jCheckPepsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckPepsiMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Qty");

        jCheckCocacola.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckCocacola.setText("Coca-cola");
        jCheckCocacola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckCocacolaMouseClicked(evt);
            }
        });

        jCheck7up.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheck7up.setText("7Up");
        jCheck7up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheck7upMouseClicked(evt);
            }
        });

        jCheckMuntainDew.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckMuntainDew.setText("Muntain Dew");
        jCheckMuntainDew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckMuntainDewMouseClicked(evt);
            }
        });

        jTextpepsi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextpepsi.setText("0");
        jTextpepsi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextcocacola.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextcocacola.setText("0");
        jTextcocacola.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText7up.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jText7up.setText("0");
        jText7up.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextmountaindew.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextmountaindew.setText("0");
        jTextmountaindew.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jCheckTea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckTea.setText("Tea");
        jCheckTea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckTeaMouseClicked(evt);
            }
        });

        jTexttea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTexttea.setText("0");
        jTexttea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextcoffee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextcoffee.setText("0");
        jTextcoffee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jCheckCofee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckCofee.setText("Coffee");
        jCheckCofee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckCofeeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(53, 53, 53))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheck7up)
                                .addComponent(jCheckMuntainDew)
                                .addComponent(jCheckTea)
                                .addComponent(jCheckCofee))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckPepsi)
                                    .addComponent(jCheckCocacola))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextcocacola)
                                    .addComponent(jTextpepsi)
                                    .addComponent(jText7up, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(jTextmountaindew, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(jTexttea, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(jTextcoffee, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))))
                        .addContainerGap(29, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckPepsi)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextpepsi)
                        .addGap(3, 3, 3)))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckCocacola)
                    .addComponent(jTextcocacola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheck7up)
                    .addComponent(jText7up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckMuntainDew)
                    .addComponent(jTextmountaindew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckTea)
                    .addComponent(jTexttea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckCofee)
                    .addComponent(jTextcoffee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Cost of Foods");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Cost of Drinks");

        jlblCostoffoods.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblCostoffoods.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblCostoffoods.setText("0");
        jlblCostoffoods.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlblCostofdrinks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblCostofdrinks.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblCostofdrinks.setText("0");
        jlblCostofdrinks.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Taka");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Taka");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jlblCostoffoods, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jlblCostofdrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblCostoffoods, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCostofdrinks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Sub total :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Vat :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Total :");

        jlblsubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblsubTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblsubTotal.setText("0");
        jlblsubTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlblVat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblVat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblVat.setText("0");
        jlblVat.setToolTipText("");
        jlblVat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Taka");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Taka");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Taka");

        jlblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblTotal.setText("0");
        jlblTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblsubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(jlblVat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel14))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblsubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblVat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Currency Converter");

        jcmbCurrency.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcmbCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one", "Dollar", "Rupee", "Euro", " " }));

        jlblConvert.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblConvert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblConvert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        jBtnConvert.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnConvert.setText("Convert");
        jBtnConvert.setBorder(new javax.swing.border.MatteBorder(null));
        jBtnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConvertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcmbCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcmbCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlblConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Calculator");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Net Payable");

        jlblNetpayable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblNetpayable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblNetpayable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Cash Paid");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Return Amount");

        jlblRetuenamount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblRetuenamount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblRetuenamount.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextCashpaid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextCashpaid.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextCashpaid.setToolTipText("");
        jTextCashpaid.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBtncalculate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtncalculate.setText("Calculate");
        jBtncalculate.setBorder(new javax.swing.border.MatteBorder(null));
        jBtncalculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtncalculateMouseClicked(evt);
            }
        });
        jBtncalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtncalculateActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("(+/-)Using Rounding");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblRetuenamount, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblNetpayable, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jTextCashpaid))))
                .addGap(28, 28, 28))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jBtncalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblNetpayable, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextCashpaid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblRetuenamount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBtncalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jBtnTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnTotal.setText("Total");
        jBtnTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnTotalMouseClicked(evt);
            }
        });
        jBtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTotalActionPerformed(evt);
            }
        });

        jBtnReceipt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnReceipt.setText("Receipt");
        jBtnReceipt.setAutoscrolls(true);
        jBtnReceipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnReceiptMouseClicked(evt);
            }
        });
        jBtnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReceiptActionPerformed(evt);
            }
        });

        jBtnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnReset.setText("Reset");
        jBtnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnResetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnResetMouseEntered(evt);
            }
        });
        jBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetActionPerformed(evt);
            }
        });

        jBtnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnExit.setText("Exit");
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jBtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197)
                .addComponent(jBtnReceipt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(jBtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193)
                .addComponent(jBtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jBtnTotal)
                .addComponent(jBtnReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Receipt", jPanel9);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Coin Changing Algorithm", jPanel10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConvertActionPerformed
        double Taka = Double.parseDouble(jlblTotal.getText());
        if(jcmbCurrency.getSelectedItem().equals("Rupee"))
        {
            String cConvert1 = String.format("₹ %.2f",Taka*.79);
            jlblConvert.setText(cConvert1);

        }
        else if(jcmbCurrency.getSelectedItem().equals("Dollar"))
        {
            String cConvert2 = String.format("$ %.2f",Taka*0.012);
            jlblConvert.setText(cConvert2);
        }
        else if(jcmbCurrency.getSelectedItem().equals("Euro"))
        {
            String cConvert3 = String.format("€ %.2f",Taka*0.011);
            jlblConvert.setText(cConvert3);
        }

    }//GEN-LAST:event_jBtnConvertActionPerformed

    private void jBtncalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtncalculateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtncalculateActionPerformed

    private void jBtnTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTotalMouseClicked
        double cTotal1 = Double.parseDouble(jlblCostofdrinks.getText());
        double cTotal2 = Double.parseDouble(jlblCostoffoods.getText());
        double vat = (cTotal1+cTotal2)/100;
        String ivat = String.format("%.2f", vat);
        jlblVat.setText(ivat);
        double subTotal = (cTotal1+cTotal2);
        String isubTotal = String.format("%.2f", subTotal);
        jlblsubTotal.setText(isubTotal);
        double allTotal = (cTotal1+cTotal2+vat);
        String iTotal = String.format("%.2f", allTotal);
        jlblTotal.setText(iTotal);
        String bTotal = String.format("%.0f", allTotal);
        jlblNetpayable.setText(bTotal);

    }//GEN-LAST:event_jBtnTotalMouseClicked

    private void jBtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTotalActionPerformed

    }//GEN-LAST:event_jBtnTotalActionPerformed

    private void jBtnReceiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnReceiptMouseClicked
        
        double Food1 = Double.parseDouble(jTextsingara.getText());
        double Food2 = Double.parseDouble(jTextsomosa.getText());
        double Food3 = Double.parseDouble(jTextnoodles.getText());
        double Food4 = Double.parseDouble(jTextburger.getText());
        double Food5 = Double.parseDouble(jTextchickenroll.getText());
        double Food6 = Double.parseDouble(jTextpizza.getText());
        double Drink1 = Double.parseDouble(jTextpepsi.getText());
        double Drink2 = Double.parseDouble(jTextcocacola.getText());
        double Drink3 = Double.parseDouble(jText7up.getText());
        double Drink4 = Double.parseDouble(jTextmountaindew.getText());
        double Drink5 = Double.parseDouble(jTexttea.getText());
        double Drink6 = Double.parseDouble(jTextcoffee.getText());
        double subtotal = Double.parseDouble(jlblsubTotal.getText());
        double vat = Double.parseDouble(jlblVat.getText());
        double total = Double.parseDouble(jlblTotal.getText());
        double Netpayable = Double.parseDouble(jlblNetpayable.getText());        
        double Cashpaid = Double.parseDouble(jTextCashpaid.getText());
        double returnamount = Double.parseDouble(jlblRetuenamount.getText());
        int  count=0;
                
        jTextArea1.append("\n                       DIU Smart Canteen\n\tMain Campus\n-------------------------------------------------------\nSL    Item Name      Qty\tTotal\n");
        if(Food1 > 0)
        {
            count++;
            double price1=Food1 * 5.00;
            jTextArea1.append(count+".      Singara:\t     "+Food1+"\t"+price1+"\n");
        }
        if(Food2 > 0)
        {
            count++;
            double price2=Food2 * 7.00;
            jTextArea1.append(count+".      Samosa:\t     "+Food2+"\t"+price2+"\n");
        }
        if(Food3 > 0)
        {
            count++;
            double price3=Food3 * 25.00;
            jTextArea1.append(count+".      Noodles:\t     "+Food3+"\t"+price3+"\n");
        }
        if(Food4 > 0)
        {
            count++;
            double price4=Food4 * 25.00;
            jTextArea1.append(count+".      Burger:\t     "+Food4+"\t"+price4+"\n");
        }
        if(Food5 > 0)
        {
            count++;
            double price5=Food5 * 20.00;
            jTextArea1.append(count+".     Chicken Roll: "+Food5+"\t"+price5+"\n");
        }
        if(Food6 > 0)
        {
            count++;
            double price6=Food6 * 50.00;
            jTextArea1.append(count+".     Pizza:\t     "+Food6+"\t"+price6+"\n");
        }
        if(Drink1>0)
        {            
            count++;
            double price7=Drink1 * 15.00;
            jTextArea1.append(count+".     Pepsi:\t     "+Drink1+"\t"+price7+"\n");
        }
        if(Drink2>0)
        {
            count++;
            double price8=Drink2 * 15.00;
            jTextArea1.append(count+".     Coca-cola:\t     "+Drink2+"\t"+price8+"\n");
        }
        if(Drink3>0)
        {
            count++;
            double price9=Drink3 * 15.00;
            jTextArea1.append(count+".     7Up:\t     "+Drink3+"\t"+price9+"\n");
        }
        if(Drink4>0)
        {
            count++;
             double price10=Drink4 * 25.00;
            jTextArea1.append(count+".     Muntain Dew: "+Drink4+"\t"+price10+"\n");
        }
        if(Drink5>0)
        {
            count++;
            double price11=Drink5 * 6.00;
            jTextArea1.append(count+".     Tea:\t     "+Drink2+"\t"+price11+"\n");
        }
        if(Drink6>0)
        {
            count++;
            double price12=Drink6 * 10.00;
            jTextArea1.append(count+".     Coffee:\t     "+Drink6+"\t"+price12+"\n");
        }
        
        jTextArea1.append("-------------------------------------------------------\n");
        jTextArea1.append("SubTotal:\t\t"+subtotal+"\nVat:\t\t"+vat+"\n"+"Total Cost:\t\t"+total);
        jTextArea1.append("\n-------------------------------------------------------\n");
        jTextArea1.append("Netpayable:\t\t"+Netpayable+"\nCashpaid:\t\t"+Cashpaid+"\n"+"Return Amount:\t\t"+returnamount);
        jTextArea1.append("\n-------------------------------------------------------\n");
        jTextArea1.append("\tThank You :)");
        
        

        
    }//GEN-LAST:event_jBtnReceiptMouseClicked

    private void jBtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReceiptActionPerformed

        
    }//GEN-LAST:event_jBtnReceiptActionPerformed

    private void jBtnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnResetMouseClicked
    jCheck7up.setSelected(false);
    jCheckBurger.setSelected(false);
    jCheckChickenRoll.setSelected(false);
    jCheckCocacola.setSelected(false);
    jCheckCofee.setSelected(false);
    jCheckMuntainDew.setSelected(false);
    jCheckNoodles.setSelected(false);
    jCheckPepsi.setSelected(false);
    jCheckPizza.setSelected(false);
    jCheckSingara.setSelected(false);
    jCheckSomosa.setSelected(false);
    jCheckTea.setSelected(false);
    jlblNetpayable.setText(null);
    jlblRetuenamount.setText(null);
    jlblConvert.setText(null);
    jlblCostoffoods.setText("0");
    jlblCostofdrinks.setText("0");
    jlblVat.setText("0");
    jlblTotal.setText("0");        
    jlblsubTotal.setText("0");
    jText7up.setText("0");
    jTextCashpaid.setText(null);
    jTextburger.setText("0");
    jTextchickenroll.setText("0");
    jTextcocacola.setText("0");
    jTextcoffee.setText("0");
    jTextmountaindew.setText("0");
    jTextnoodles.setText("0");
    jTextpepsi.setText("0");
    jTextpizza.setText("0");
    jTextsingara.setText("0");
    jTextsomosa.setText("0");
    jTexttea.setText("0");        
    jcmbCurrency.setSelectedItem("Choose one");      
    }//GEN-LAST:event_jBtnResetMouseClicked

    private void jBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnResetActionPerformed

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtnExitActionPerformed

    private void jCheckSingaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckSingaraMouseClicked
    double cMeal = Double.parseDouble(jlblCostoffoods.getText());
        double Singara = Double.parseDouble(jTextsingara.getText());
        double iSingara = 5.00;
        if(jCheckSingara.isSelected())
        {
            i[0] = (Singara * iSingara) + cMeal;
            String pMeal = String.format("%.2f",i[0]);
            jlblCostoffoods.setText(pMeal);
        }
        if(!(jCheckSingara.isSelected()))
        {
            i[0] =  cMeal-(Singara * iSingara);
            String pMeal = String.format("%.2f",i[0]);
            jlblCostoffoods.setText(pMeal);
        }
    }//GEN-LAST:event_jCheckSingaraMouseClicked

    private void jCheckSomosaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckSomosaMouseClicked
     double cMeal = Double.parseDouble(jlblCostoffoods.getText());
        double Somosa = Double.parseDouble(jTextsomosa.getText());
        double iSomosa = 7.00;
        if(jCheckSomosa.isSelected())
        {
            i[1] = (Somosa * iSomosa) + cMeal;
            String pMeal = String.format("%.2f",i[1]);
            jlblCostoffoods.setText(pMeal);
        }   
         if(!(jCheckSomosa.isSelected()))
        {
            i[1] = cMeal - (Somosa * iSomosa);
            String pMeal = String.format("%.2f",i[1]);
            jlblCostoffoods.setText(pMeal);
        } 
    }//GEN-LAST:event_jCheckSomosaMouseClicked

    private void jCheckNoodlesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckNoodlesMouseClicked
        double cMeal = Double.parseDouble(jlblCostoffoods.getText());
        double Noodles = Double.parseDouble(jTextnoodles.getText());
        double iNoodles = 25.00;
        if(jCheckNoodles.isSelected())
        {
            i[2] = (Noodles * iNoodles) + cMeal;
            String pMeal = String.format("%.2f",i[2]);
            jlblCostoffoods.setText(pMeal);
        }
        if(!(jCheckNoodles.isSelected()))
        {
            i[2] =cMeal-(Noodles * iNoodles) ;
            String pMeal = String.format("%.2f",i[2]);
            jlblCostoffoods.setText(pMeal);
        }
    }//GEN-LAST:event_jCheckNoodlesMouseClicked

    private void jCheckBurgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBurgerMouseClicked
        double cMeal = Double.parseDouble(jlblCostoffoods.getText());
        double Burger = Double.parseDouble(jTextburger.getText());
        double iBurger = 25.00;
        if(jCheckBurger.isSelected())
        {
            i[3] = (Burger * iBurger) + cMeal;
            String pMeal = String.format("%.2f",i[3]);
            jlblCostoffoods.setText(pMeal);
        }
        if(!(jCheckBurger.isSelected()))
        {
            i[3] = cMeal-(Burger * iBurger);
            String pMeal = String.format("%.2f",i[3]);
            jlblCostoffoods.setText(pMeal);
        }
        
    }//GEN-LAST:event_jCheckBurgerMouseClicked

    private void jCheckChickenRollMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckChickenRollMouseClicked
        double cMeal = Double.parseDouble(jlblCostoffoods.getText());
        double ChickenRoll = Double.parseDouble(jTextchickenroll.getText());
        double iChickenRoll = 20.00;
        if(jCheckChickenRoll.isSelected())
        {
            i[4] = (ChickenRoll * iChickenRoll) + cMeal;
            String pMeal = String.format("%.2f",i[4]);
            jlblCostoffoods.setText(pMeal);
        }
        if(!(jCheckChickenRoll.isSelected()))
        {
            i[4] =  cMeal-(ChickenRoll * iChickenRoll);
            String pMeal = String.format("%.2f",i[4]);
            jlblCostoffoods.setText(pMeal);
        }
    }//GEN-LAST:event_jCheckChickenRollMouseClicked

    private void jCheckPizzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckPizzaMouseClicked
        double cMeal = Double.parseDouble(jlblCostoffoods.getText());
        double Pizza = Double.parseDouble(jTextpizza.getText());
        double iPizza = 50.00;
        if(jCheckPizza.isSelected())
        {
            i[5] = (Pizza * iPizza) + cMeal;
            String pMeal = String.format("%.2f",i[5]);
            jlblCostoffoods.setText(pMeal);
        }
        if(!(jCheckPizza.isSelected()))
        {
            i[5] = cMeal-(Pizza * iPizza);
            String pMeal = String.format("%.2f",i[5]);
            jlblCostoffoods.setText(pMeal);
        }
        
    }//GEN-LAST:event_jCheckPizzaMouseClicked

    private void jCheckPepsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckPepsiMouseClicked
        double cMeal = Double.parseDouble(jlblCostofdrinks.getText());
        double Pepsi = Double.parseDouble(jTextpepsi.getText());
        double iPepsi = 15.00;
        if(jCheckPepsi.isSelected())
        {
            i[6] = (Pepsi * iPepsi) + cMeal;
            String pMeal = String.format("%.2f",i[6]);
            jlblCostofdrinks.setText(pMeal);
        }
        if(!(jCheckPepsi.isSelected()))
        {
            i[6] = cMeal-(Pepsi * iPepsi);
            String pMeal = String.format("%.2f",i[6]);
            jlblCostofdrinks.setText(pMeal);
        }
    }//GEN-LAST:event_jCheckPepsiMouseClicked

    private void jCheckCocacolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckCocacolaMouseClicked
     double cMeal = Double.parseDouble(jlblCostofdrinks.getText());
        double Cocacola = Double.parseDouble(jTextcocacola.getText());
        double iCocacola = 15.00;
        if(jCheckCocacola.isSelected())
        {
            i[7] = (Cocacola * iCocacola) + cMeal;
            String pMeal = String.format("%.2f",i[7]);
            jlblCostofdrinks.setText(pMeal);
        }
        if(!(jCheckCocacola.isSelected()))
        {
            i[7] = cMeal-(Cocacola * iCocacola);
            String pMeal = String.format("%.2f",i[7]);
            jlblCostofdrinks.setText(pMeal);
        }
    }//GEN-LAST:event_jCheckCocacolaMouseClicked

    private void jCheck7upMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheck7upMouseClicked
        double cMeal = Double.parseDouble(jlblCostofdrinks.getText());
        double up7 = Double.parseDouble(jText7up.getText());
        double iup7 = 15.00;
        if(jCheck7up.isSelected())
        {
            i[8] = (up7 * iup7) + cMeal;
            String pMeal = String.format("%.2f",i[8]);
            jlblCostofdrinks.setText(pMeal);
        }
        if(!(jCheck7up.isSelected()))
        {
            i[8] = cMeal-(up7 * iup7);
            String pMeal = String.format("%.2f",i[8]);
            jlblCostofdrinks.setText(pMeal);
        }
    }//GEN-LAST:event_jCheck7upMouseClicked

    private void jCheckMuntainDewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckMuntainDewMouseClicked
    double cMeal = Double.parseDouble(jlblCostofdrinks.getText());
        double MuntainDew = Double.parseDouble(jTextmountaindew.getText());
        double iMuntainDew = 25.00;
        if(jCheckMuntainDew.isSelected())
        {
            i[9] = (MuntainDew * iMuntainDew) + cMeal;
            String pMeal = String.format("%.2f",i[9]);
            jlblCostofdrinks.setText(pMeal);
        }
        if(!(jCheckMuntainDew.isSelected()))
        {
            i[9] = cMeal-(MuntainDew * iMuntainDew);
            String pMeal = String.format("%.2f",i[9]);
            jlblCostofdrinks.setText(pMeal);
        }
    }//GEN-LAST:event_jCheckMuntainDewMouseClicked

    private void jCheckTeaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckTeaMouseClicked
        double cMeal = Double.parseDouble(jlblCostofdrinks.getText());
        double tea = Double.parseDouble(jTexttea.getText());
        double itea = 6.00;
        if(jCheckTea.isSelected())
        {
            i[10] = (tea * itea) + cMeal;
            String pMeal = String.format("%.2f",i[10]);
            jlblCostofdrinks.setText(pMeal);
        }
        if(!(jCheckTea.isSelected()))
        {
            i[10] = cMeal-(tea * itea);
            String pMeal = String.format("%.2f",i[10]);
            jlblCostofdrinks.setText(pMeal);
        }
    }//GEN-LAST:event_jCheckTeaMouseClicked

    private void jCheckCofeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckCofeeMouseClicked
        double cMeal = Double.parseDouble(jlblCostofdrinks.getText());
        double Cofee = Double.parseDouble(jTextcoffee.getText());
        double iCofee = 10.00;
        if(jCheckCofee.isSelected())
        {
            i[11] = (Cofee * iCofee) + cMeal;
            String pMeal = String.format("%.2f",i[11]);
            jlblCostofdrinks.setText(pMeal);
        }
        if(!(jCheckCofee.isSelected()))
        {
            i[11] = cMeal-(Cofee * iCofee);
            String pMeal = String.format("%.2f",i[11]);
            jlblCostofdrinks.setText(pMeal);
        }
    }//GEN-LAST:event_jCheckCofeeMouseClicked

    private void jBtncalculateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtncalculateMouseClicked
         double netpayable = Double.parseDouble(jlblNetpayable.getText());
        double CashPaid = Double.parseDouble(jTextCashpaid.getText());
        double iamount = CashPaid - netpayable;
            String amount = String.format("%.2f",iamount);
            jlblRetuenamount.setText(amount);
            int i,j,k,s;            
    
    s=(int)iamount;
    jTextArea2.append("It may become easy to give the change if\n");
    while(s>0)
    {
        for(i=0;i<7;i++)
        {
            if(c[i]<=s)
            {
                k=s/c[i];
                jTextArea2.append("\n"+c[i]+" Taka\t"+k+" Times");                
                s=s-k*c[i];
            }

        }



    }
    jTextArea2.append(" uses\n\n--------------Thank You--------------");

    }//GEN-LAST:event_jBtncalculateMouseClicked

    private void jBtnResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnResetMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnResetMouseEntered

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnConvert;
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnReceipt;
    private javax.swing.JButton jBtnReset;
    private javax.swing.JButton jBtnTotal;
    private javax.swing.JButton jBtncalculate;
    private javax.swing.JCheckBox jCheck7up;
    private javax.swing.JCheckBox jCheckBurger;
    private javax.swing.JCheckBox jCheckChickenRoll;
    private javax.swing.JCheckBox jCheckCocacola;
    private javax.swing.JCheckBox jCheckCofee;
    private javax.swing.JCheckBox jCheckMuntainDew;
    private javax.swing.JCheckBox jCheckNoodles;
    private javax.swing.JCheckBox jCheckPepsi;
    private javax.swing.JCheckBox jCheckPizza;
    private javax.swing.JCheckBox jCheckSingara;
    private javax.swing.JCheckBox jCheckSomosa;
    private javax.swing.JCheckBox jCheckTea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jText7up;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextCashpaid;
    private javax.swing.JTextField jTextburger;
    private javax.swing.JTextField jTextchickenroll;
    private javax.swing.JTextField jTextcocacola;
    private javax.swing.JTextField jTextcoffee;
    private javax.swing.JTextField jTextmountaindew;
    private javax.swing.JTextField jTextnoodles;
    private javax.swing.JTextField jTextpepsi;
    private javax.swing.JTextField jTextpizza;
    private javax.swing.JTextField jTextsingara;
    private javax.swing.JTextField jTextsomosa;
    private javax.swing.JTextField jTexttea;
    private javax.swing.JComboBox<String> jcmbCurrency;
    private javax.swing.JLabel jlblConvert;
    private javax.swing.JLabel jlblCostofdrinks;
    private javax.swing.JLabel jlblCostoffoods;
    private javax.swing.JLabel jlblNetpayable;
    private javax.swing.JLabel jlblRetuenamount;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JLabel jlblVat;
    private javax.swing.JLabel jlblsubTotal;
    // End of variables declaration//GEN-END:variables
}
